# Advanced Aliases for Kubernetes Kubectl.
# Use with caution
#

alias k="kubectl"
alias ka="kubectl apply"
alias kc="kubectl config current-context"
alias kd="kubectl describe"
alias kdl="kubectl delete"
alias kdld="kubectl delete deploy"
alias kdlh="kubectl delete hpa"
alias kdlj="kubectl delete job"
alias kdlp="kubectl delete pod"
alias kdls="kubectl delete service"
alias kdd="kubectl describe deploy"
alias kdds="kubectl describe deploy --namespace=kube-system"
alias kdh="kubectl describe hpa"
alias kdhs="kubectl describe hpa --namespace=kube-system"
alias kdi="kubectl describe ingress"
alias kdis="kubectl describe ingress --namespace=kube-system"
alias kdj="kubectl describe job"
alias kdjs="kubectl describe job --namespace=kube-system"
alias kdn="kubectl describe nodes"
alias kdp="kubectl describe pod"
alias kdps="kubectl describe pod --namespace=kube-system"
alias kds="kubectl describe service"
alias kdss="kubectl describe service --namespace=kube-system"
alias ke="kubectl exec -it"
alias kei="kubectl edit ingress"
alias kl="kubectl logs"
alias kls="kubectl logs --namespace=kube-system"
alias kgl="kubectl logs"
alias kgls="kubectl logs --namespace=kube-system"
alias klf="kubectl logs -f"
alias klfs="kubectl logs -f --namespace=kube-system"
alias kglf="kubectl logs -f"
alias kglfs="kubectl logs -f --namespace=kube-system"
alias kgcm="kubectl get configmap"
alias kgcms="kubectl get configmap --namespace=kube-system"
alias kgd="kubectl get deploy"
alias kgds="kubectl get deploy --namespace=kube-system"
alias kgh="kubectl get hpa"
alias kghs="kubectl get hpa --namespace=kube-system"
alias kgi="kubectl get ingress"
alias kgis="kubectl get ingress --namespace=kube-system"
alias kgj="kubectl get jobs"
alias kgjs="kubectl get jobs --namespace=kube-system"
alias kgn="kubectl get nodes"
alias kgns="kubectl get nodes --namespace=kube-system"
alias kgp="kubectl get pods"
alias kgps="kubectl get pods --namespace=kube-system"
alias kgs="kubectl get services"
alias kgss="kubectl get services --namespace=kube-system"
alias kp="kubectl proxy"
